import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { 
  Bot, 
  Shield, 
  TrendingUp, 
  Zap, 
  CheckCircle, 
  Star,
  ArrowRight,
  Play,
  Users,
  Award,
  Lock,
  Globe,
  ChevronDown,
  ChevronUp
} from 'lucide-react';

interface LivePrice {
  symbol: string;
  price: number;
  change: number;
  changePercent: number;
}

function LandingPage() {
  const [livePrices, setLivePrices] = useState<LivePrice[]>([
    { symbol: 'BTC/USD', price: 67523, change: 845, changePercent: 1.25 },
    { symbol: 'ETH/USD', price: 3215, change: -28, changePercent: -0.87 },
    { symbol: 'BNB/USD', price: 542, change: 12, changePercent: 2.26 },
    { symbol: 'ADA/USD', price: 0.45, change: 0.02, changePercent: 4.65 }
  ]);

  const [openFaq, setOpenFaq] = useState<number | null>(null);

  useEffect(() => {
    // Simulate live price updates
    const interval = setInterval(() => {
      setLivePrices(prev => prev.map(price => ({
        ...price,
        price: price.price + (Math.random() - 0.5) * 100,
        change: (Math.random() - 0.5) * 200,
        changePercent: (Math.random() - 0.5) * 5
      })));
    }, 3000);

    return () => clearInterval(interval);
  }, []);

  const features = [
    {
      icon: <Bot className="w-8 h-8 text-blue-400" />,
      title: "AI-Powered Trading",
      description: "24/7 smart trade execution with advanced machine learning algorithms"
    },
    {
      icon: <Shield className="w-8 h-8 text-green-400" />,
      title: "Risk Management Tools",
      description: "Stop-loss, trailing stop, auto-rebalancing for maximum protection"
    },
    {
      icon: <Globe className="w-8 h-8 text-purple-400" />,
      title: "Multi-Exchange Support",
      description: "Trade on Binance, Coinbase, Kraken & more from one platform"
    },
    {
      icon: <Lock className="w-8 h-8 text-yellow-400" />,
      title: "Non-Custodial Security",
      description: "You keep control of your funds with encrypted API connections"
    }
  ];

  const testimonials = [
    {
      name: "Rajesh Kumar",
      role: "Crypto Trader",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=64&h=64&fit=crop&crop=face",
      quote: "TradeBitco.in helped me increase my portfolio by 45% in just 3 months. The AI predictions are incredibly accurate!"
    },
    {
      name: "Priya Sharma",
      role: "Investment Analyst",
      image: "https://images.unsplash.com/photo-1494790108755-2616b612b786?w=64&h=64&fit=crop&crop=face",
      quote: "The tax assistant feature saved me hours during IT filing. Perfect for Indian crypto investors!"
    },
    {
      name: "Amit Patel",
      role: "Tech Entrepreneur",
      image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=64&h=64&fit=crop&crop=face",
      quote: "Finally, a platform that understands Indian regulations. The multi-exchange support is game-changing."
    }
  ];

  const faqs = [
    {
      question: "Is my crypto safe with TradeBitco.in?",
      answer: "Yes! We use a non-custodial approach - your funds stay in your exchange accounts. We only connect via secure API keys with trading permissions, never withdrawal access."
    },
    {
      question: "Can I withdraw my funds anytime?",
      answer: "Absolutely! Since we don't hold your funds, you have complete control. You can withdraw directly from your exchange accounts anytime."
    },
    {
      question: "How does the profit-sharing model work?",
      answer: "Our optional profit-sharing model takes 10% of profits generated by our AI trading bot. If the bot doesn't make profits, you pay nothing extra."
    },
    {
      question: "Which exchanges do you support?",
      answer: "We support major exchanges including Binance, Coinbase, Kraken, Bitfinex, and popular Indian exchanges like CoinDCX and WazirX."
    },
    {
      question: "Is TradeBitco.in compliant with Indian regulations?",
      answer: "Yes! We're designed specifically for Indian users with built-in tax compliance, IT return-ready reports, and adherence to Indian crypto regulations."
    }
  ];

  return (
    <div className="min-h-screen bg-gray-900 text-white">
      {/* Navigation */}
      <nav className="fixed top-0 w-full bg-gray-900/95 backdrop-blur-sm border-b border-gray-800 z-50">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <Bot className="w-8 h-8 text-blue-400" />
            <span className="text-xl font-bold">TradeBitco.in</span>
          </div>
          <div className="hidden md:flex items-center space-x-8">
            <a href="#features" className="hover:text-blue-400 transition-colors">Features</a>
            <a href="#how-it-works" className="hover:text-blue-400 transition-colors">How It Works</a>
            <a href="#pricing" className="hover:text-blue-400 transition-colors">Pricing</a>
            <a href="#faq" className="hover:text-blue-400 transition-colors">FAQ</a>
          </div>
          <div className="flex items-center space-x-4">
            <Link to="/login" className="hover:text-blue-400 transition-colors">Login</Link>
            <Link to="/register" className="bg-blue-600 hover:bg-blue-700 px-4 py-2 rounded-lg transition-colors">
              Sign Up
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section className="pt-24 pb-16 relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-900/20 to-purple-900/20"></div>
        <div className="container mx-auto px-4 relative z-10">
          <div className="text-center max-w-4xl mx-auto">
            <h1 className="text-5xl md:text-7xl font-bold mb-6 bg-gradient-to-r from-blue-400 to-purple-400 bg-clip-text text-transparent">
              AI-Powered Bitcoin Trading for Maximum Profits, Minimum Risk
            </h1>
            <p className="text-xl md:text-2xl text-gray-300 mb-8 leading-relaxed">
              Automate your crypto trades with cutting-edge AI, real-time analytics, and secure exchange integrations.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
              <Link 
                to="/register" 
                className="bg-blue-600 hover:bg-blue-700 px-8 py-4 rounded-lg text-lg font-semibold transition-all transform hover:scale-105 flex items-center space-x-2"
              >
                <span>Start Free Trial</span>
                <ArrowRight className="w-5 h-5" />
              </Link>
              <button className="border border-gray-600 hover:border-blue-400 px-8 py-4 rounded-lg text-lg font-semibold transition-all flex items-center space-x-2">
                <Play className="w-5 h-5" />
                <span>See How It Works</span>
              </button>
            </div>
          </div>
        </div>
        
        {/* Floating Animation Elements */}
        <div className="absolute top-20 left-10 animate-bounce">
          <div className="bg-blue-500/20 p-4 rounded-full">
            <Bot className="w-8 h-8 text-blue-400" />
          </div>
        </div>
        <div className="absolute top-40 right-20 animate-pulse">
          <div className="bg-green-500/20 p-4 rounded-full">
            <TrendingUp className="w-8 h-8 text-green-400" />
          </div>
        </div>
      </section>

      {/* Live Stats Banner */}
      <section className="bg-gray-800 py-4 border-y border-gray-700">
        <div className="container mx-auto px-4">
          <div className="flex overflow-x-auto space-x-8 scrollbar-hide">
            {livePrices.map((price, index) => (
              <div key={index} className="flex items-center space-x-2 whitespace-nowrap">
                <span className="font-semibold">{price.symbol}:</span>
                <span className="text-lg font-bold">${price.price.toLocaleString()}</span>
                <span className={`flex items-center ${price.changePercent >= 0 ? 'text-green-400' : 'text-red-400'}`}>
                  {price.changePercent >= 0 ? '▲' : '▼'} {Math.abs(price.changePercent).toFixed(2)}%
                </span>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Key Benefits */}
      <section id="features" className="py-20">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">Why Choose TradeBitco.in?</h2>
            <p className="text-xl text-gray-400">Advanced features designed for serious crypto traders</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <div key={index} className="bg-gray-800/50 backdrop-blur-sm p-6 rounded-xl border border-gray-700 hover:border-blue-500/50 transition-all transform hover:scale-105">
                <div className="mb-4">{feature.icon}</div>
                <h3 className="text-xl font-bold mb-2">{feature.title}</h3>
                <p className="text-gray-400">{feature.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section id="how-it-works" className="py-20 bg-gray-800/30">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">How It Works</h2>
            <p className="text-xl text-gray-400">Get started in just 3 simple steps</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="text-center">
              <div className="bg-blue-600 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-6 text-2xl font-bold">1</div>
              <h3 className="text-2xl font-bold mb-4">Connect Exchange</h3>
              <p className="text-gray-400">Secure API connection to Binance, Coinbase, Kraken, and more</p>
            </div>
            <div className="text-center">
              <div className="bg-purple-600 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-6 text-2xl font-bold">2</div>
              <h3 className="text-2xl font-bold mb-4">Choose Strategy</h3>
              <p className="text-gray-400">Select AI-powered or custom trading strategies based on your risk profile</p>
            </div>
            <div className="text-center">
              <div className="bg-green-600 w-16 h-16 rounded-full flex items-center justify-center mx-auto mb-6 text-2xl font-bold">3</div>
              <h3 className="text-2xl font-bold mb-4">Start Trading</h3>
              <p className="text-gray-400">Let our AI bot work for you 24/7 with advanced risk management</p>
            </div>
          </div>
        </div>
      </section>

      {/* Feature Highlights */}
      <section className="py-20">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            <div>
              <h2 className="text-4xl font-bold mb-6">Advanced Trading Dashboard</h2>
              <div className="space-y-4">
                <div className="flex items-center space-x-3">
                  <CheckCircle className="w-6 h-6 text-green-400" />
                  <span>Real-time portfolio tracking across multiple exchanges</span>
                </div>
                <div className="flex items-center space-x-3">
                  <CheckCircle className="w-6 h-6 text-green-400" />
                  <span>AI-powered market analysis and predictions</span>
                </div>
                <div className="flex items-center space-x-3">
                  <CheckCircle className="w-6 h-6 text-green-400" />
                  <span>Automated tax reporting for Indian compliance</span>
                </div>
                <div className="flex items-center space-x-3">
                  <CheckCircle className="w-6 h-6 text-green-400" />
                  <span>Advanced risk management tools</span>
                </div>
              </div>
              <div className="mt-8">
                <Link to="/register" className="bg-blue-600 hover:bg-blue-700 px-6 py-3 rounded-lg font-semibold transition-colors">
                  Try Dashboard Free
                </Link>
              </div>
            </div>
            <div className="relative">
              <div className="bg-gradient-to-br from-gray-800 to-gray-900 p-6 rounded-xl border border-gray-700">
                <div className="bg-gray-700 h-64 rounded-lg flex items-center justify-center">
                  <div className="text-center">
                    <TrendingUp className="w-16 h-16 text-blue-400 mx-auto mb-4" />
                    <p className="text-gray-400">Interactive Dashboard Preview</p>
                  </div>
                </div>
              </div>
              <div className="absolute -top-4 -right-4 bg-green-500 text-white px-3 py-1 rounded-full text-sm font-semibold">
                Live Data
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Social Proof */}
      <section className="py-20 bg-gray-800/30">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">Trusted by Thousands of Traders</h2>
            <p className="text-xl text-gray-400">See what our users are saying</p>
          </div>
          
          {/* Testimonials */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-16">
            {testimonials.map((testimonial, index) => (
              <div key={index} className="bg-gray-800/50 p-6 rounded-xl border border-gray-700">
                <div className="flex items-center mb-4">
                  {[...Array(5)].map((_, i) => (
                    <Star key={i} className="w-5 h-5 text-yellow-400 fill-current" />
                  ))}
                </div>
                <p className="text-gray-300 mb-4">"{testimonial.quote}"</p>
                <div className="flex items-center space-x-3">
                  <img src={testimonial.image} alt={testimonial.name} className="w-10 h-10 rounded-full" />
                  <div>
                    <div className="font-semibold">{testimonial.name}</div>
                    <div className="text-sm text-gray-400">{testimonial.role}</div>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Partner Logos */}
          <div className="text-center">
            <p className="text-gray-400 mb-8">Integrated with leading exchanges</p>
            <div className="flex flex-wrap justify-center items-center gap-8 opacity-60">
              <div className="text-2xl font-bold">Binance</div>
              <div className="text-2xl font-bold">Coinbase</div>
              <div className="text-2xl font-bold">Kraken</div>
              <div className="text-2xl font-bold">CoinDCX</div>
              <div className="text-2xl font-bold">WazirX</div>
            </div>
          </div>
        </div>
      </section>

      {/* Pricing Plans */}
      <section id="pricing" className="py-20">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">Choose Your Plan</h2>
            <p className="text-xl text-gray-400">Start free, upgrade when you're ready</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 max-w-6xl mx-auto">
            {/* Free Plan */}
            <div className="bg-gray-800/50 p-8 rounded-xl border border-gray-700">
              <h3 className="text-2xl font-bold mb-2">Free</h3>
              <div className="text-4xl font-bold mb-6">₹0<span className="text-lg text-gray-400">/month</span></div>
              <ul className="space-y-3 mb-8">
                <li className="flex items-center space-x-3">
                  <CheckCircle className="w-5 h-5 text-green-400" />
                  <span>Basic portfolio tracking</span>
                </li>
                <li className="flex items-center space-x-3">
                  <CheckCircle className="w-5 h-5 text-green-400" />
                  <span>Limited alerts</span>
                </li>
                <li className="flex items-center space-x-3">
                  <CheckCircle className="w-5 h-5 text-green-400" />
                  <span>Educational content</span>
                </li>
              </ul>
              <Link to="/register" className="w-full bg-gray-700 hover:bg-gray-600 py-3 rounded-lg font-semibold transition-colors block text-center">
                Get Started
              </Link>
            </div>

            {/* Pro Plan */}
            <div className="bg-gray-800/50 p-8 rounded-xl border-2 border-blue-500 relative">
              <div className="absolute -top-4 left-1/2 transform -translate-x-1/2 bg-blue-500 text-white px-4 py-1 rounded-full text-sm font-semibold">
                Most Popular
              </div>
              <h3 className="text-2xl font-bold mb-2">Pro</h3>
              <div className="text-4xl font-bold mb-6">₹999<span className="text-lg text-gray-400">/month</span></div>
              <ul className="space-y-3 mb-8">
                <li className="flex items-center space-x-3">
                  <CheckCircle className="w-5 h-5 text-green-400" />
                  <span>Full AI trading bot</span>
                </li>
                <li className="flex items-center space-x-3">
                  <CheckCircle className="w-5 h-5 text-green-400" />
                  <span>All exchanges</span>
                </li>
                <li className="flex items-center space-x-3">
                  <CheckCircle className="w-5 h-5 text-green-400" />
                  <span>Advanced analytics</span>
                </li>
                <li className="flex items-center space-x-3">
                  <CheckCircle className="w-5 h-5 text-green-400" />
                  <span>Tax assistant</span>
                </li>
              </ul>
              <Link to="/register" className="w-full bg-blue-600 hover:bg-blue-700 py-3 rounded-lg font-semibold transition-colors block text-center">
                Start Pro Trial
              </Link>
            </div>

            {/* Elite Plan */}
            <div className="bg-gray-800/50 p-8 rounded-xl border border-gray-700">
              <h3 className="text-2xl font-bold mb-2">Elite</h3>
              <div className="text-4xl font-bold mb-6">₹4,999<span className="text-lg text-gray-400">/month</span></div>
              <ul className="space-y-3 mb-8">
                <li className="flex items-center space-x-3">
                  <CheckCircle className="w-5 h-5 text-green-400" />
                  <span>Everything in Pro</span>
                </li>
                <li className="flex items-center space-x-3">
                  <CheckCircle className="w-5 h-5 text-green-400" />
                  <span>DeFi integration</span>
                </li>
                <li className="flex items-center space-x-3">
                  <CheckCircle className="w-5 h-5 text-green-400" />
                  <span>Custom strategies</span>
                </li>
                <li className="flex items-center space-x-3">
                  <CheckCircle className="w-5 h-5 text-green-400" />
                  <span>Priority support</span>
                </li>
              </ul>
              <Link to="/register" className="w-full bg-purple-600 hover:bg-purple-700 py-3 rounded-lg font-semibold transition-colors block text-center">
                Go Elite
              </Link>
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section id="faq" className="py-20 bg-gray-800/30">
        <div className="container mx-auto px-4">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold mb-4">Frequently Asked Questions</h2>
            <p className="text-xl text-gray-400">Everything you need to know about TradeBitco.in</p>
          </div>
          <div className="max-w-3xl mx-auto">
            {faqs.map((faq, index) => (
              <div key={index} className="mb-4">
                <button
                  onClick={() => setOpenFaq(openFaq === index ? null : index)}
                  className="w-full bg-gray-800/50 p-6 rounded-lg border border-gray-700 text-left flex items-center justify-between hover:border-blue-500/50 transition-colors"
                >
                  <span className="font-semibold">{faq.question}</span>
                  {openFaq === index ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
                </button>
                {openFaq === index && (
                  <div className="bg-gray-700/50 p-6 rounded-b-lg border-x border-b border-gray-700">
                    <p className="text-gray-300">{faq.answer}</p>
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="py-20">
        <div className="container mx-auto px-4 text-center">
          <h2 className="text-5xl font-bold mb-6">Start Trading Smarter Today</h2>
          <p className="text-xl text-gray-400 mb-8 max-w-2xl mx-auto">
            Join thousands of traders who are already using AI to maximize their crypto profits
          </p>
          <Link 
            to="/register" 
            className="bg-blue-600 hover:bg-blue-700 px-12 py-4 rounded-lg text-xl font-semibold transition-all transform hover:scale-105 inline-flex items-center space-x-2"
          >
            <span>Get Started Now – It's Free</span>
            <ArrowRight className="w-6 h-6" />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-800 py-12 border-t border-gray-700">
        <div className="container mx-auto px-4">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div>
              <div className="flex items-center space-x-2 mb-4">
                <Bot className="w-8 h-8 text-blue-400" />
                <span className="text-xl font-bold">TradeBitco.in</span>
              </div>
              <p className="text-gray-400">
                AI-powered cryptocurrency trading platform designed for Indian investors.
              </p>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Product</h3>
              <ul className="space-y-2 text-gray-400">
                <li><a href="#features" className="hover:text-white transition-colors">Features</a></li>
                <li><a href="#pricing" className="hover:text-white transition-colors">Pricing</a></li>
                <li><a href="#" className="hover:text-white transition-colors">API</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Security</a></li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Company</h3>
              <ul className="space-y-2 text-gray-400">
                <li><a href="#" className="hover:text-white transition-colors">About</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Blog</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Careers</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Contact</a></li>
              </ul>
            </div>
            <div>
              <h3 className="font-semibold mb-4">Legal</h3>
              <ul className="space-y-2 text-gray-400">
                <li><a href="#" className="hover:text-white transition-colors">Terms of Service</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Privacy Policy</a></li>
                <li><a href="#" className="hover:text-white transition-colors">Disclaimer</a></li>
              </ul>
            </div>
          </div>
          <div className="border-t border-gray-700 mt-8 pt-8 flex flex-col md:flex-row items-center justify-between">
            <p className="text-gray-400">
              © 2024 TradeBitco.in. All rights reserved. | Cryptocurrency trading involves risk.
            </p>
            <div className="flex items-center space-x-4 mt-4 md:mt-0">
              <a href="#" className="text-gray-400 hover:text-white transition-colors">Twitter</a>
              <a href="#" className="text-gray-400 hover:text-white transition-colors">Telegram</a>
              <a href="#" className="text-gray-400 hover:text-white transition-colors">LinkedIn</a>
              <a href="#" className="text-gray-400 hover:text-white transition-colors">YouTube</a>
            </div>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default LandingPage;